# filepath: /home/sarmaasis/projects/portfolio/serverless.yml
service: portfolio-ssr

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'