name: Deploy to Lambda

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci

    - run: npm run prepare:deploy

    - name: Package Lambda
      run: |
        mkdir lambda-package
        cp -r dist dist-lambda lambda-package/
        cp dist-lambda/index.js lambda-package/
        cd lambda-package && zip -r ../lambda.zip .

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        function_name: portfolio-ssr
        zip_file: lambda.zip